services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.4
    container_name: elasticsearch-filebeat
    environment:
      - discovery.type=single-node
      - cluster.name=SpetnickiyDI-filebeat
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock: -1
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.4
    container_name: kibana-filebeat
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: nginx-filebeat
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
    command: nginx -g 'daemon off;'

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.2.4
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./nginx/logs:/var/log/nginx:ro
    depends_on:
      elasticsearch:
        condition: service_healthy
      nginx:
        condition: service_started