services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.4
    container_name: es-task5
    environment:
      - discovery.type=single-node
      - cluster.name=task5-cluster
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.4
    container_name: kibana-task5
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy

  python-app:
    image: python:3.9-alpine
    container_name: python-app
    volumes:
      - ./app:/app
      - ./logs/app:/var/log/app
    working_dir: /app
    command: >
      sh -c "
      pip install json-log-formatter &&
      python app.py
      "

  logstash:
    image: docker.elastic.co/logstash/logstash:9.2.4
    container_name: logstash-task5
    volumes:
      - ./logstash/config/app.conf:/usr/share/logstash/pipeline/app.conf
    ports:
      - "5044:5044"
    depends_on:
      elasticsearch:
        condition: service_healthy

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.2.4
    container_name: filebeat-task5
    user: root
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs/app:/var/log/app:ro
    depends_on:
      - logstash
      - python-app