filebeat.inputs:
  - type: filestream
    id: python-app
    paths:
      - /var/log/app/app.log
    parsers:
      - ndjson:
          target: ""
          overwrite_keys: true

output.logstash:
  hosts: ["logstash:5044"]